workInfo:
  title: "Choral BWV 659"
  fullTitle: "Nun komm' der Heiden Heiland"
  composer: "J.S. Bach"
  workId: "bwv659"
  movementName: "Choral"
  externalURL: "https://en.wikipedia.org/wiki/Great_Eighteen_Chorale_Preludes"

files:
  svgPath: "bwv659_optimized.svg"
  notesPath: "bwv659_json_notes.json"
  audioPath: "bwv659.mp3"
  
musicalStructure:
  totalDurationSeconds: 204.00
  totalMeasures: 34
  visualLeadTimeSeconds: 0

